[theme.overrides]
idle_bg = "#2E3440"
idle_fg = "#f3f4f5"
info_bg = "#EBCB8B"
info_fg = "#2E3440"
good_bg = "#A3BE8C"
good_fg = "#2E3440"
warning_bg = "#BF616A"
warning_fg = "#2E3440"
separator = " "
separator_bg = "auto"
separator_fg = "auto"

[icons]
name = "awesome5"
[icons.overrides]

# # Vpn
[[block]]
block = "custom"
command = "~/.local/bin/check-vpn"
interval = 25
hide_when_empty = true
json = true
[block.theme_overrides]
info_bg = "#8FBCBB"

# Taskwarrior
[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/taskwarrior/taskwarrior-active"
interval = 25
hide_when_empty = true
json = true
[block.theme_overrides]
info_bg = "#8FBCBB"

[[block]]
block = "taskwarrior"
interval = 30
format = "{count} tasks {filter_name}"
format_singular = "{count} task {filter_name}"
format_everything_done = "all good ({filter_name})"
warning_threshold = 15
critical_threshold = 25
[block.theme_overrides]
warning_bg = "#EBCB8B"
warning_fg = "#2E3440"
critical_bg = "#BF616A"
critical_fg = "#2E3440"
[[block.filters]]
name = "ready"
filter = "+READY"
[[block.filters]]
name = "blocking"
filter = "+BLOCKING -BLOCKED"
# TODO create a filter for tasks today

#TODO.txt counter
[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/taskwarrior/taskwarrior-counter"
interval = 60
hide_when_empty = true

# #TODO.txt status
# [[block]]
# block = "custom"
# command = "~/.config/i3status-rust/scripts/todotxt-status/todotxt-status"
# interval = 18
# hide_when_empty = true
# json = true
# [block.theme_overrides]
# info_bg = "#8FBCBB"

[[block]]
block = "sound"
format = "{volume}"
driver = "auto"

# #TODO.txt counter
# [[block]]
# block = "custom"
# command = "~/.config/i3status-rust/scripts/todotxt-counter/todotxt-counter"
# interval = 60
# hide_when_empty = true

[[block]]
block = "pacman"
interval = 600
format = "{both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux |linux-lts|linux-zen)"
aur_command = "yay -Qua"
on_click = "alacritty -e sudo pacman -Syu"
[block.theme_overrides]
critical_bg = "#BF616A"

[[block]]
block = "networkmanager"
primary_only = true
on_click = "alacritty -e nmtui"
device_format = "{icon} {ap}"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "{available}"
unit = "GB"
interval = 20
warning = 30.0
alert = 10.0

[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = false
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
