[theme.overrides]
idle_bg = "#2E3440"
idle_fg = "#f3f4f5"
info_bg = "#EBCB8B"
info_fg = "#2E3440"
good_bg = "#A3BE8C"
good_fg = "#2E3440"
warning_bg = "#BF616A"
warning_fg = "#2E3440"
separator = " "
separator_bg = "auto"
separator_fg = "auto"

[icons]
icons = "awesome6"

# # Vpn
[[block]]
block = "custom"
command = "~/.local/bin/check-vpn"
interval = 25
hide_when_empty = true
json = true
[block.theme_overrides]
info_bg = "#8FBCBB"

# Vimwiki Inbox counter
# [[block]]
# block = "custom"
# command = "vimwiki-inbox-count"
# interval = 20
# hide_when_empty = true

# Github notification counter
[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/github/notifications"
interval = 40
hide_when_empty = true

# Taskwarrior
# [[block]]
# block = "custom"
# command = "~/.config/i3status-rust/scripts/taskwarrior/taskwarrior-active"
# interval = "once"
# watch_files = ["~/.task/undo.data", "~/.taskrc"]
# hide_when_empty = true
# json = true
# [block.theme_overrides]
# info_bg = "#8FBCBB"
# 
# # Taskwarrior inbox
# [[block]]
# block = "custom"
# command = "~/.config/i3status-rust/scripts/taskwarrior/taskwarrior-inbox"
# interval = "once"
# watch_files = ["~/.task/undo.data", "~/.taskrc"]
# hide_when_empty = true
# 
# # Taskwarrior counter
# [[block]]
# block = "custom"
# command = "~/.config/i3status-rust/scripts/taskwarrior/taskwarrior-counter"
# interval = "once"
# hide_when_empty = true
# watch_files = ["~/.task/undo.data", "~/.taskrc"]

# Todoist overdue
[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/todoist/overdue"
interval = 40
hide_when_empty = true
json = true

# Todoist now
[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/todoist/now"
interval = 40
hide_when_empty = true
json = true
[block.theme_overrides]
info_bg = "#8FBCBB"

# Todoist today
[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/todoist/today"
interval = 40
hide_when_empty = true

[[block]]
block = "sound"
format = "$volume $icon "
driver = "auto"

[[block]]
block = "pacman"
interval = 600
format = "{both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux |linux-lts|linux-zen)"
aur_command = "yay -Qua"
[block.theme_overrides]
critical_bg = "#BF616A"

[[block]]
block = "net"
format = " $icon $ssid "

[[block]]
block = "cpu"
interval = 4

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "$available"
alert_unit = "GB"
interval = 20
warning = 30.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents"

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %d/%m %R')"

[[block]]
block = "battery"
missing_format = "missing"
format = " $percentage $icon "
full_format = " $icon $percentage"
not_charging_format = " $icon $percentage"
