# TODO: get these colors global somehow
[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#2E3440"
idle_fg = "#f3f4f5"
info_bg = "#8FBCBB"
info_fg = "#2E3440"
good_bg = "#A3BE8C"
good_fg = "#2E3440"
warning_bg = "#BF616A"
warning_fg = "#2E3440"
separator = " "
separator_bg = "auto"
separator_fg = "auto"

[icons]
name = "awesome5"
[icons.overrides]

[[block]]
block = "keyboard_layout"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "{available} ({used} / {total})"
unit = "GB"
interval = 20
warning = 30.0
alert = 10.0

[[block]]
block = "pacman"
interval = 600
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux |linux-lts|linux-zen)"
aur_command = "yay -Qua"

[[block]]
block = "networkmanager"
primary_only = true

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{Mup}%"
# format_swap = "{SUp}%"

[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = false
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "load"
interval = 2
format = "{1m}"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"
