#!/usr/bin/env bash
# Dependencies:
# - timewarrior (timew)
# - ripgrep
# - awk
#
# TODO:
# - [ ] make it possible to use without timewarrior

action=$1
shift
item=$1


function usage {
	echo "  $(basename $0)"
	echo "    Handle which todo's you are currently working on"
	echo "    Uses timewarrior to track time spent on tasks. You can only work on one task at a time"
	echo ""
	echo "    Examples:"
	echo "      $ $TODO_SH $(basename $0)       - Show currently working todo"
	echo "      $ $TODO_SH $(basename $0) 12    - Start working on todo 12"
	echo "      $ $TODO_SH $(basename $0) done  - Complete currently working todo"
	echo "      $ $TODO_SH $(basename $0) clear - Stop working"
	echo "      $ $TODO_SH $(basename $0) stop  - Stop working"
	echo ""
	exit
}

function get_current_number {
	number=$($TODO_FULL_SH -p lsp A | awk 'NR==1 { print ($1 == "--") ? "0" : $1 }' | bc)
	echo $number
}

function now_show {
	number=$(get_current_number)
	if [ "$number" = "0" ]; then
		echo "Nothing is currently being worked on"
	else
		$TODO_FULL_SH -P lsp A | head -n 1
		display_recording "$number"
	fi
}

function now_start {
	number=$(get_current_number)
	if [ "$number" = "0" ]; then
		$TODO_FULL_SH pri $item A
	else
		$TODO_FULL_SH pri $number B
		stop_recording
		$TODO_FULL_SH pri $item A
	fi
	start_recording $item
}

function now_clear {
	number=$(get_current_number)
	if [ "$number" = "0" ]; then
		$TODO_FULL_SH pri $item A
		echo "Nothing is currently being worked on"
	else
		$TODO_FULL_SH pri $number B
		stop_recording
	fi
}

function now_done {
	number=$(get_current_number)
	if [ "$number" = "0" ]; then
		echo "Nothing is currently being worked on"
	else
		$TODO_FULL_SH done $number
		stop_recording
	fi
}

function start_recording() {
	todo=$($TODO_FULL_SH -P -p ls $1 | head -n 1)
	desc=$(echo $todo | awk '{ for (i = 1; i <= NF; i++) if ($i !~ /+|@/ && i > 1) print $i; }')
	project=$(echo $todo | awk '{ for (i = 1; i <= NF; i++) if ($i ~ /+/) print $i }')
	echo ""
	timew start $project "$desc"
}

function stop_recording {
	echo ""
	timew stop
}

function display_recording {
	echo ""
	timew
}


[ "$action" = "usage" ] && usage

if [ -z $item ]; then
	now_show
elif [[ "$item" = "clear" || "$item" = "c" || "$item" = "stop" ]]; then
	now_clear
elif [[ "$item" = "done" || "$item" = "d" ]]; then
	now_done
else
	now_start $item
fi
