#!/usr/bin/env bash

action=$1

function usage {
	echo "  $(basename $0)"
	echo "    Show what should be done today."
	echo ""
	echo "    Example:"
	echo "      $ $TODO_SH $(basename $0)"
	echo ""
	exit
}

function list {
	$TODO_FULL_SH lsp A-B
}

[ "$action" = "usage" ] && usage

list
