#!/bin/env bash

set -e

NEEDS_PUSH='{"icon":"update", "text": "push taskwarrior changes", "state": "Info"}'
NEEDS_PULL='{"icon":"net_down", "text": "taskwarrior is out of sync", "state": "Warning"}'
HIDE='{"icon":"", "text": "", "state": "Idle"}'

cd ~/.task

# TEST=$(git ls-remote origin -h refs/heads/master | cut -f1)
# TEST2=$(git log --pretty=%H ...refs/heads/master^ | head -n 1)

if git status | rg -q "Changes not staged for commit"; then
  echo $NEEDS_PUSH
else
  echo $HIDE
fi
