#!/bin/env bash

set -e

print_info() {
  echo "{\"icon\":\"tasks\", \"text\": \"$@\", \"state\": \"Idle\"}"
}

INFO="$(todoist list --filter 'today' | wc -l) today"

if [[ "$INFO" != "0" ]]; then
  print_info $INFO
else
  print_info "All good"
fi
